tracker_type: bytetrack # tracker type

# Tracking arguments
track_high_thresh: 0.6 # threshold for the first association
track_low_thresh: 0.1 # threshold for the second association
new_track_thresh: 0.7 # threshold for init new track if the detection does not match any tracks
track_buffer: 30 # buffer to calculate the time when to remove tracks
match_thresh: 0.8 # threshold for matching tracks
fuse_score: True # Whether to fuse confidence scores with the iou distances before matching
min_box_area: 10  # threshold for min box areas
aspect_ratio_thresh: 1.6 # threshold for aspect ratio

# CMC arguments
gmc_method: None # method of global motion compensation

# ReID arguments (not used in ByteTracker)
with_reid: False  # ByteTracker doesn't use ReID features
